### ISSUE TITLE
non riesco a far girare il mio Makefile

### ISSUE THREAD

**Issue by alebarbolini** [pburgio/CPP_For_MMR#1]
@pburgio  Riesco a far girare il suo codice "Hello_World". Ho creato anche la mia cartella "Hello_World_Alessia" con all'interno il file C++ ed il Makefile ma dal terminale il make mi dice "no targets. stops."

**Comment by AlessandroPierro** [comment]
Allega il Makefile così vediamo se va bene

**Comment by alebarbolini** [comment]
Ho risolto, non avevo salvato il file
