### ISSUE TITLE
Installazione compilatore gcc

### ISSUE THREAD

**Issue by Sadamicis** [pburgio/CPP_For_MMR#2]
Ciao ra tutti, ho un problema nell' installare gcc
salvatore@salvatore-HP-250-G7-Notebook-PC:~/CPP_For_MMR/Code/Exercises$ sudo apt install gcc
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Alcuni pacchetti non possono essere installati. Questo può voler dire
che è stata richiesta una situazione impossibile oppure, se si sta
usando una distribuzione in sviluppo, che alcuni pacchetti richiesti
non sono ancora stati creati o sono stati rimossi da Incoming.
Le seguenti informazioni possono aiutare a risolvere la situazione:

I seguenti pacchetti hanno dipendenze non soddisfatte:
 gcc : Dipende: gcc-7 (>= 7.3.0-12~) ma non sta per essere installato
       Raccomanda: libc6-dev ma non sta per essere installato oppure
                   libc-dev
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

**Comment by pburgio** [comment]
@AlessandroPierro potete aiutarlo?

**Comment by pburgio** [comment]
@Sadamicis puoi usare la funzione "Code" (qui sopra a dx) per abbellire un po' il post ;)

`salvatore@salvatore-HP-250-G7-Notebook-PC:~/CPP_For_MMR/Code/Exercises$ sudo apt install gcc
`

**Comment by AlessandroPierro** [comment]
Prova con 
`sudo apt autoremove
auto apt install build-essential `

**Comment by Sadamicis** [comment]
No, ho provato con `sudo apt autoremove`, ma quando vado a installare gcc con `sudo apt install gcc` mi da o stesso errore scritto sopra.

**Comment by Sadamicis** [comment]
![immagine](https://user-images.githubusercontent.com/94184947/144033956-199021be-5754-40fb-8906-235a8550c67e.png)

**Comment by AlessandroPierro** [comment]
Direi di no. Questo comando cosa ti dà?

`sudo apt install build-essential`

**Comment by Sadamicis** [comment]
Ovviamente ho provato a installare le dipendenze che mi dice mancanti, ma mi richiede ulteriori dipendenze oppure msg di questo tipo:
`salvatore@salvatore-HP-250-G7-Notebook-PC:~$ sudo apt install libc-dev`
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Nota, viene selezionato "libc6-dev" al posto di "libc-dev"
Alcuni pacchetti non possono essere installati. Questo può voler dire
che è stata richiesta una situazione impossibile oppure, se si sta
usando una distribuzione in sviluppo, che alcuni pacchetti richiesti
non sono ancora stati creati o sono stati rimossi da Incoming.
Le seguenti informazioni possono aiutare a risolvere la situazione:

I seguenti pacchetti hanno dipendenze non soddisfatte:
 libc6-dev : Dipende: libc6 (= 2.27-3ubuntu1) ma la versione 2.27-3ubuntu1.4 sta per essere installata
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.
